# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
#  name: repo-name

  # A short description of the repository that will show up on GitHub
  description: easyTemplateLib - an easyScience library

  # A URL with more information about the repository
  homepage: https://easyTemplateLib.github.io/

  # A comma-separated list of topics to set on the repository
  topics: science, modeling

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: CC0000
    description: An issue with the system.

  - name: feature
    # If including a `#`, make sure to wrap it with quotes!
    color: 336699
    description: New functionality.

  - name: first-timers-only
    color: 0386dd
    # include the old name to rename an existing label
    oldname: Help Wanted

  - name: major
    color: dd0316
    description: Apply to bump the version by x.0.0

  - name: minor
    color: dd6903
    description: Apply to bump the version by 0.x.0

  - name: patch
    color: fbe204
    description: Apply to bump the version by 0.0.x

# Milestones: define milestones for Issues and Pull Requests
milestones:
  - title: Repo setup
    description: The repo needs to be configured to meet your needs
    # The state of the milestone. Either `open` or `closed`
    state: open

# Collaborators: give specific users access to this repository.
# See https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator for available options
#collaborators:
#  - username: bkeepers
#    # Note: Only valid on organization-owned repositories.
#    # The permission to grant the collaborator. Can be one of:
#    # * `pull` - can pull, but not push to or administer this repository.
#    # * `push` - can pull and push, but not administer this repository.
#    # * `admin` - can pull, push and administer this repository.
#    permission: push
#
#  - username: hubot
#    permission: pull
#
## See https://developer.github.com/v3/teams/#add-or-update-team-repository for available options
#teams:
#  - name: core
#    # The permission to grant the team. Can be one of:
#    # * `pull` - can pull, but not push to or administer this repository.
#    # * `push` - can pull and push, but not administer this repository.
#    # * `admin` - can pull, push and administer this repository.
#    permission: admin
#  - name: docs
#    permission: push

branches:
  - name: master
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: null
