# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
#     if: endsWith(github.ref, '/master') && ! contains(github.repository, 'easyTemplateLib')
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Create branches
      run: |
        git config --global user.name 'On Create Bot'
        git checkout -b develop
        git push origin develop:develop
        git checkout -b release
        git push origin release:release
    - uses: mattsb42/repo-manager@v1.1.0
      with:
        github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        config-file: probot-settings.yml
        debug: true
    - name: Commit Changes
      run: |
        git commit -am "Automated Repo Maker"
        git push --force
